### ISSUE TITLE
[BUG]: The search-again option breaks ytfzf

### ISSUE THREAD

**Issue by pitsi** [pystardust/ytfzf#613]
### Describe the bug
The search-again option (either as a command line parameter or as a parameter in the configuration file) breaks ytfzf in a weird way. Once the playback, instead of returning to the results, it just returns to fzf "menu" which waits for input in a menu with zero entries! And the only way to exit it is to completely close the terminal.
Pressing ctrl+c shows what is behind fzf for a split second, and it mentions ~/.cache/ytfzf as far as I can read.

### To Reproduce
1) Start ytfzf with the `--search-again` parameter.
2) Search for anything and select something to play when fzf comes up with the results.
3) Wait for it to finish (or just press q to make mpv quit before it ends).
4) Notice the emptyness on the screenshot below.

### Expected behavior
Ytfzf should return to the list where fzf waits for user input. Fzf works like it should here, it just has nothing to display as a list.

### Screenshots
![2022-12-16-181444_800x600_scrot](https://user-images.githubusercontent.com/5880037/208141620-94879d61-0a3c-42a4-9cba-c7bc431a7bf9.png)

### Information
 - OS: Debian testing/unstable x64
 - Terminal: Urxvt and alacritty
 - Ytfzf version: 2.5.3
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`): 
`lrwxrwxrwx 1 root root 4 Sep  1 17:11 /usr/bin/sh -> dash `

### Additional context
Pictured above is alacritty, fzf is on v0.35, below is my conf.sh and ytfzf was working fine until 2.5.2.
Last but not least, I want to clean anything that is under the `~/.cache` folder, but I am keeping it for now, if it helps troubleshoot the issue.
```
search_source=hist
search_again=1
video_pref=140
#video_pref=22
#invidious_instance=
notify_playing=1
scrape=yt
```

**Comment by Euro20179** [comment]
This should now be fixed in the development branch.

**Comment by pitsi** [comment]
Thank you! Since debian decided to package it, I no longer use it as another standalone script from my ~/bin folder.
If I patch it manually ( = one straight edit on /usr/bin/ytfzf), do I have to add all the other patches before this one to make it work like it used to?

**Comment by pitsi** [comment]
Thank you. I will patch it in ~15 minutes, because I have some work to do right now, and report back.

**Comment by pitsi** [comment]
It did not work :( 
My file here does not have the 2898 lines that the one in the commit has, it stops at 2746, so I had to improvise. 
I changed these lines, which are 2709 to 2441 from
```
main() {
	while :; do
		# calls the interface
		run_interface
		handle_keypress "$keypress_file" || case "$?" in 2) break ;; 3) continue ;; esac
		handle_actions "$ytfzf_selected_urls" || { [ "$?" -eq 2 ] || continue && break; }

		[ $enable_hist -eq 1 ] && add_to_hist "$ytfzf_video_json_file" < "$ytfzf_selected_urls"

		# nothing below needs to happen if  this is empty (causes bugs when this is not here)
		[ ! -s "$ytfzf_selected_urls" ] && break

		# shellcheck disable=SC2015
		if [ "$info_to_print" ]; then
		    data="$(get_requested_info "$ytfzf_selected_urls")"
		    display_text_wrapper "$data"
		    handle_info_wait_action
		    case "$?" in 3) continue ;; 2) break ;; esac
		fi
		open_url_handler "$ytfzf_selected_urls"
		close_url_handler "$url_handler"

		[ "$is_loop" -eq 0 ] && break
	done

    # doing this after the loop allows for -l and -s to coexist
    while [ "$search_again" -eq 1 ] ; do
        clean_up
        initial_search=""
        main
    done
}
main
```
to
```
main() {
	while :; do
		# calls the interface
		run_interface
		handle_keypress "$keypress_file" || case "$?" in 2) break ;; 3) continue ;; esac
		handle_actions "$ytfzf_selected_urls" || { [ "$?" -eq 2 ] || continue && break; }

		[ $enable_hist -eq 1 ] && add_to_hist "$ytfzf_video_json_file" < "$ytfzf_selected_urls"

		# nothing below needs to happen if  this is empty (causes bugs when this is not here)
		[ ! -s "$ytfzf_selected_urls" ] && break

		# shellcheck disable=SC2015
		if [ "$info_to_print" ]; then
		    data="$(get_requested_info "$ytfzf_selected_urls")"
		    display_text_wrapper "$data"
		    handle_info_wait_action
		    case "$?" in 3) continue ;; 2) break ;; esac
		fi
		open_url_handler "$ytfzf_selected_urls"
		close_url_handler "$url_handler"

		[ "$is_loop" -eq 0 ] && break
	done
}

main
    # doing this after the loop allows for -l and -s to coexist
    while [ "$search_again" -eq 1 ] ; do
        clean_up
        initial_search=""
        main
    done
```
but the problem is still there. Can I clean the cache folder now?

**Comment by Euro20179** [comment]
make sure to change the `initial_search=""` line to the new line in the patch.

**Comment by pitsi** [comment]
> make sure to change the `initial_search=""` line to the new line in the patch.

Can you please be more specific about that? I am not that experienced with bash :(

**Comment by Euro20179** [comment]
You put this
```bash

    # doing this after the loop allows for -l and -s to coexist
    while [ "$search_again" -eq 1 ] ; do
        clean_up
        initial_search=""
        main
    done
```

You need to put this

```bash
# doing this after the loop allows for -l and -s to coexist
while [ "$search_again" -eq 1 ] ; do
    clean_up
    init_and_make_search "" "prompt"
    main
done
```

The difference is that instead of just `initial_search=""` (resetting the variable), it's running the `init_and_make_search` function.

**Comment by pitsi** [comment]
This is what I now have at the lines above
```
# doing this after the loop allows for -l and -s to coexist
while [ "$search_again" -eq 1 ] ; do
	clean_up
	initial_search="" "prompt"
	main
done
```
but it still behaves like before. I even removed the indents from the left side.
I will remove the package and reuse the script from the development branch until a new version is released.

**Comment by Euro20179** [comment]
do not put `initial_search="" "prompt"`, put `init_and_make_search "" "prompt"`

**Comment by pitsi** [comment]
Ok this fixed it. I am posting my change again, just in case
```
main

# doing this after the loop allows for -l and -s to coexist
while [ "$search_again" -eq 1 ] ; do
	clean_up
	init_and_make_search "" "prompt"
	main
done
```
There is a missing "=" after the word search on line 6. I do not know if it is important, I am only mentioning it.
It does work, but it does not get me back to history once playback is done. Please note that I use `search_source=hist` as seen in my config above.

**Comment by Euro20179** [comment]
>  Please note that I use search_source=hist as seen in my config above.

**Comment by pitsi** [comment]
Closing as fixed in 2.5.4. I did not notice it was released here 1 week ago, I was waiting for the the package update on my distro :(

**Comment by pitsi** [comment]
One thing I just noticed. The search again parameter seems to work only once.

I launch `ytfzf -q`, so as to grab entries from its search history, it finds stuff, it plays the one I choose and then it asks for a new search, instead of returning to the search history. Is this normal?

**Comment by Euro20179** [comment]
oddly, yes it was hardcoded to only show the prompt with `-s`, this has been fixed in the development branch. (please note that -q will use a prompt as a backup if nothing was selected from history, I will likely be changing this.)

**Comment by pitsi** [comment]
The 1+ month late reply :(
I just noticed that v2.5.5 was released 5 days ago. Does it solve the issue I mentioned above?
Debian is under freeze now, so I doubt it will reach the repo before summer.

**Comment by Euro20179** [comment]
> The 1+ month late reply :(

All good, and yes this is fixed in 2.5.5

**Comment by pitsi** [comment]
Thank you :)
If it does not reach the repo, I will probably end up using it as a standalone script like like I used to before debian decided to package it. Meanwhile, I have more serious issues to solve with mpv and the new yt-dlp.
