### ISSUE TITLE
Support for styling and number of search results

### ISSUE THREAD

**Issue by paniash** [pystardust/ytfzf#94]
Currently, the default number of search results seems to be some number less than 40. I think an option in `conf.sh` could be added to include a user-defined number of search results. 

Currently the previews are on the left and fzf on right. An option to swap the two would be nice. Thanks!

**Comment by pystardust** [comment]
I think we will need to modify the scrape algorithm to get more than 40 results. ( we might need to simulate scrolling down on youtube search). I am not entirely sure how to do it. For previews Euro has implemented it. Check out the sample conf.sh.

**Comment by paniash** [comment]
@pystardust The partial fix works fine but I have a minor issue. I've written a very rudimentary dmenu wrapper around ytfzf so that I don't have to open my terminal manually. Setting `preview_side="right"` in `conf.sh` works expected, provided I manually open my terminal and run `ytfzf -t`. 

My custom wrapper however, doesn't work when used with `preview_side="right"`. The thumbnails get awkwardly centered instead of being placed to the right. This problem does not arise though if I set `preview_side="left"`. Not sure what's going on.

This is my script:
```sh
arg=$(echo "$1" | dmenu -i -p 'Search YouTube: ')
alacritty -e ytfzf -t $arg
```

**Comment by pystardust** [comment]
@Euro20179 
We will have an issue when using ytfzf right preview from a script ( `tput` won't work).

The current task is to place the images on the right half of the terminal. But since we don't know the size, we have no clue where to place them.
With left this is not an issue cause we always place them at `x=2;y=10`.

**Comment by Euro20179** [comment]
I may be misunderstanding the problem, but it seems to work fine at least for me.

**Comment by pystardust** [comment]
@paniash Did you update `ytfzf`, we had this issue after the first commit. I think it seems to have be fixed now. I just ran it in the same way you mention with `st -e ./script` and it seems to be working.

**Comment by paniash** [comment]
@pystardust I just updated and still have the same issue.

**Comment by paniash** [comment]
This is how it appears sometimes on alacritty:
![pic-full-210307-0059-02](https://user-images.githubusercontent.com/59497618/110229108-08091180-7f2d-11eb-9e1b-8513539899ed.png)

**Comment by paniash** [comment]
Ok, tried it with the development branch as well. The issue still persists.

**Comment by pystardust** [comment]
```sh
#!/bin/sh

[ -z "$TTY_COLS" ] && export TTY_COLS="$(tput cols)"
FIFO="/tmp/ytfzf-test-pipe"



start_ub () {
	[ -e "$FIFO" ] || mkfifo "$FIFO"
	# To keep fifo open
	ueberzug layer --parser json < "$FIFO" & 
	exec 3>"$FIFO"
}
stop_ub () {
	# close the redirection
	exec 3>&-
	rm "$FIFO" 
}


preview_img () {
	WIDTH=$FZF_PREVIEW_COLUMNS
	HEIGHT=$FZF_PREVIEW_LINES

	thumb_width=$WIDTH
	thumb_height=$((HEIGHT - 2))

	thumb_x=$(($TTY_COLS / 2 + 3))
	thumb_y=10
	read ueberzug_info << EOF
{ "action": "add", "identifier": "test", "path": "$1", "x": $thumb_x, "y": $thumb_y, "scaler": "fit_contain", "width": $thumb_width, "height": $thumb_height }
EOF
	printf "%s\n" "$ueberzug_info" > "$FIFO"
}

remove_img () {
	read ueberzug_info << EOF
{ "action": "remove", "identifier": "test" }
EOF
	printf "%s\n" "$ueberzug_info" > "$FIFO"
}

if [ "$#" -ge 1 ]; then
	regex='.*\.(png|jpg|gif)$'
	echo "$1" | grep -E -q "$regex" && { preview_img "$1" ; exit; }
	remove_img
	[ -d "$1" ] && { ls "$1" ; exit ; } || { cat "$1" ;}
	exit;
fi


start_ub
ls -1 | fzf --preview-window "right:50%:wrap" \
	--preview "sh $0 {}"
stop_ub
```
Try this script out. I have rewritten only the parts thare necessary for right image preview.
The script doesn't take arguments. Run it in a directory that contains images, and browse through the images.

**Comment by paniash** [comment]
@pystardust Thanks for the script. I've tried it out but the images are weirdly placed towards the right. Attaching a screenshot for reference.

![pic-full-210310-1950-49](https://user-images.githubusercontent.com/59497618/110643304-f8622500-81d9-11eb-8b04-f9a5e0d4da7c.png)

**Comment by Joseph65** [comment]
i think you can look up for more than 30 results with the current youtube-dl with 
youtube-dl ytsearch50:google

**Comment by paniash** [comment]
@pystardust I would say that it's slightly better now, but not as good as when rendered with left preview.

**Comment by pystardust** [comment]
Thats really strange. The image should have taked width = `102` columns, which is half your terminal size.
`tty_cols` is the number of columns in your terminal and `fzf_width` is the width ueberzug will display the image with

**Comment by pystardust** [comment]
You could always fix this by adjusting the width manually
```sh
	local thumb_width=$WIDTH
```
>  line 388 in the dev branch

Try changing `thumb_width` to 150 over here
@paniash 
I am not able to think of a general solution that would be compatible with everyone since I am not able to reproduce this issue. But increasing this value will definitly fix the issue for you .

**Comment by Euro20179** [comment]
you could update to 2.1 and try using the `--fzf-opts='--height 100'` option

**Comment by bambirombi** [comment]
I have this in the config: --pages=50, but I continue to see only 20 search results. What should I put in the config file?
Version: 2.4.0-1

**Comment by Euro20179** [comment]
`pages_to_scrape=50`

**Comment by bambirombi** [comment]
@Euro20179 After `pages_to_scrape=50` I have far more than 50 results. After searching three different things I obtain 477, 535 and 528 results. Any way to limit this? Moreover, it is a bit slow.

**Comment by Euro20179** [comment]
Scrape less pages to limit it,
scraping a lot of things is slow; making requests is slow.

**Comment by bambirombi** [comment]
@Euro20179 Thanks! I have set it to `pages_to_scrape=3`. Now it gives 60 results.
